% will pull the data from files generated by the simple rewiring

wb = '/Users/erich/Documents/Programming/Research/Bassler/Summer 2015-Summer 2016/WeibinResults/seq316_rAll_simple_rewire/';
wb20s = 'SimpleRewire_ccg_triangle_N316r2.0*';
wb25s = 'SimpleRewire_ccg_triangle_N316r2.5*';
wb30s = 'SimpleRewire_ccg_triangle_N316r3.0*';
wb35s = 'SimpleRewire_ccg_triangle_N316r3.5*';
% SimpleRewire_ccg_triangle_N316r2.5Sq864.txt

final_20_tri_wb_simprew = [];
final_25_tri_wb_simprew = [];
final_30_tri_wb_simprew = [];
final_35_tri_wb_simprew = [];

final_20_ccg_wb_simprew = [];
final_25_ccg_wb_simprew = [];
final_30_ccg_wb_simprew = [];
final_35_ccg_wb_simprew = []; 

cd(wb);
wb20f = dir(wb20s);
wb25f = dir(wb25s);
wb30f = dir(wb30s);
wb35f = dir(wb35s);

for i = 1:1:1000
    cd(wb)
    
    wb20_name = wb20f(i).name;
    disp(wb20_name);
    wb20_data = dlmread(wb20_name,' ',1,0);
    wb20_tri = wb20_data(:,1);
    
    wb25_name = wb25f(i).name;
    disp(wb25_name);
    wb25_data = dlmread(wb25_name,' ',1,0);
    wb25_tri = wb25_data(:,1);
    
    wb30_name = wb30f(i).name;
    disp(wb30_name);
    wb30_data = dlmread(wb30_name,' ',1,0);
    wb30_tri = wb30_data(:,1);
   
    wb35_name = wb35f(i).name;
    disp(wb35_name);
    wb35_data = dlmread(wb35_name,' ',1,0);
    wb35_tri = wb35_data(:,1);

    final_20_tri_wb_simprew = horzcat(final_20_tri_wb_simprew, wb20_tri');
    final_25_tri_wb_simprew = horzcat(final_25_tri_wb_simprew, wb25_tri');
    final_30_tri_wb_simprew = horzcat(final_30_tri_wb_simprew, wb30_tri');
    final_35_tri_wb_simprew = horzcat(final_35_tri_wb_simprew, wb35_tri');
    
    final_20_ccg_wb_simprew = horzcat(final_20_ccg_wb_simprew, wb20_data(:,2)');
    final_25_ccg_wb_simprew = horzcat(final_25_ccg_wb_simprew, wb25_data(:,2)');
    final_30_ccg_wb_simprew = horzcat(final_30_ccg_wb_simprew, wb30_data(:,2)');
    final_35_ccg_wb_simprew = horzcat(final_35_ccg_wb_simprew, wb35_data(:,2)');
end

clear *name *data *f *s i clear *tri