% will compare the number of triangles generated for regular graphs
% generated by the regular graph triangle probability

er = '/Users/erich/Documents/Programming/Research/Bassler/Summer 2015-Summer 2016/ExponentialModel/ERGM_RegularGraphs/figures_2017_08_14/tridist_2017_08_15/';
ers = 'tridist_*';

cd(er);
erf = dir(ers);

ertri = NaN([1,316]);
ertri_std = NaN([1,316]);
ertri_min = NaN([1,316]);
ertri_max = NaN([1,316]);


for i = 1:1:316
    %er
    cd(er);
    er_name = string(erf(i).name);
    disp(er_name);
    er_data = dlmread(er_name);
    er_tri = er_data(:,1);
    
    
    % get index
    er_name = replace(er_name,'tridist_','');
    er_name = replace(er_name, '.txt','');
    inder = int32(str2double(er_name))+1;
    
    % store
    ertri(inder) = mean(er_tri);
    ertri_std(inder) = std(er_tri);
    ertri_min(inder) = min(er_tri);
    ertri_max(inder) = max(er_tri);
    
end