% will find the histogram of the triangles generated by the ERGM
% graphs found by Erich and Weibin.
er = '/Users/erich/Documents/Programming/Research/Bassler/Summer 2015-Summer 2016/ExponentialModel/ExponentialModel/results_dense_2017_08_09/';
er20s = 'TriSqrGcc_316_*_-2.0_10000.txt';
er25s = 'TriSqrGcc_316_*_-2.5_10000.txt';
er30s = 'TriSqrGcc_316_*_-3.0_10000.txt';
er35s = 'TriSqrGcc_316_*_-3.5_10000.txt';
%TriSqrGcc_316_1_-2.0_1000.txt

wb = '/Users/erich/Documents/Programming/Research/Bassler/Summer 2015-Summer 2016/WeibinResults/seq316_dbroot_NoSelfLoop/';
wb20s = 'ccg_triangle_2_*';
wb25s = 'ccg_triangle_2.5_*';
wb30s = 'ccg_triangle_3_*';
wb35s = 'ccg_triangle_3.5_*';
%ccg_triangle_2_1.txt

final_20_tri_er = [];
final_25_tri_er = [];
final_30_tri_er = [];
final_35_tri_er = [];

final_20_tri_wb = [];
final_25_tri_wb = [];
final_30_tri_wb = [];
final_35_tri_wb = [];

final_20_ccg_er = [];
final_25_ccg_er = [];
final_30_ccg_er = [];
final_35_ccg_er = [];

final_20_ccg_wb = [];
final_25_ccg_wb = [];
final_30_ccg_wb = [];
final_35_ccg_wb = [];

cd(er);
er20f = dir(er20s);
er25f = dir(er25s);
er30f = dir(er30s);
er35f = dir(er35s);

cd(wb);
wb20f = dir(wb20s);
wb25f = dir(wb25s);
wb30f = dir(wb30s);
wb35f = dir(wb35s);

for i = 1:1:1000
    cd(er);
    er20_name = er20f(i).name;
    disp(er20_name);
    er20_data = dlmread(er20_name);
    er20_tri = er20_data(:,2);
    
    er25_name = er25f(i).name;
    disp(er25_name);
    er25_data = dlmread(er25_name);
    er25_tri = er25_data(:,2);
    
    er30_name = er30f(i).name;
    disp(er30_name);
    er30_data = dlmread(er30_name);
    er30_tri = er30_data(:,2);
    
    er35_name = er35f(i).name;
    disp(er35_name);
    er35_data = dlmread(er35_name);
    er35_tri = er35_data(:,2);
    
    wb
    cd(wb);
    wb20_name = wb20f(i).name;
    disp(wb20_name);
    wb20_data = dlmread(wb20_name,' ',1,0);
    wb20_tri = wb20_data(:,2);
    
    wb25_name = wb25f(i).name;
    disp(wb25_name);
    wb25_data = dlmread(wb25_name,' ',1,0);
    wb25_tri = wb25_data(:,2);
    
    wb30_name = wb30f(i).name;
    disp(wb30_name);
    wb30_data = dlmread(wb30_name,' ',1,0);
    wb30_tri = wb30_data(:,2);
   
    wb35_name = wb35f(i).name;
    disp(wb35_name);
    wb35_data = dlmread(wb35_name,' ',1,0);
    wb35_tri = wb35_data(:,2);

    append to final
    final_20_tri_er = horzcat(final_20_tri_er, er20_tri');
    final_25_tri_er = horzcat(final_25_tri_er, er25_tri');
    final_30_tri_er = horzcat(final_30_tri_er, er30_tri');
    final_35_tri_er = horzcat(final_35_tri_er, er35_tri');
    
    final_20_tri_wb = horzcat(final_20_tri_wb, wb20_tri');
    final_25_tri_wb = horzcat(final_25_tri_wb, wb25_tri');
    final_30_tri_wb = horzcat(final_30_tri_wb, wb30_tri');
    final_35_tri_wb = horzcat(final_35_tri_wb, wb35_tri');
    
    final_20_ccg_er = horzcat(final_20_ccg_er, er20_data(:,4)');
    final_25_ccg_er = horzcat(final_25_ccg_er, er25_data(:,4)');
    final_30_ccg_er = horzcat(final_30_ccg_er, er30_data(:,4)');
    final_35_ccg_er = horzcat(final_35_ccg_er, er35_data(:,4)');
    
    final_20_ccg_wb = horzcat(final_20_ccg_wb, wb20_data(:,3)');
    final_25_ccg_wb = horzcat(final_25_ccg_wb, wb25_data(:,3)');
    final_30_ccg_wb = horzcat(final_30_ccg_wb, wb30_data(:,3)');
    final_35_ccg_wb = horzcat(final_35_ccg_wb, wb35_data(:,3)');
end

clear *name  *f *s i clear *tri *data